behaviors:
  DriveCar:
    trainer_type: ppo
    hyperparameters:
      batch_size: 5120
      buffer_size: 204800
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.15
      lambd: 0.95
      num_epoch: 4
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 4
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 200000000
    time_horizon: 1000
    summary_freq: 50000
